export const equipment = [
  { id: "GEN-01", name: "Diesel Generator", location: "Power House" },
  { id: "MDB-01", name: "Main Distribution Board", location: "Power House" },
  { id: "AC-01", name: "Air Compressor", location: "Utilities" },
  { id: "AD-01", name: "Air Dryer", location: "Utilities" },
  { id: "CWP-01", name: "Cooling Water Pump", location: "Utilities" },
  { id: "CT-01", name: "Cooling Tower", location: "Utilities" },
  { id: "FWP-01", name: "Boiler Feed Pump", location: "Utilities" },
  { id: "BLR-01", name: "Steam Boiler", location: "Utilities" },
  { id: "CNV-01", name: "Infeed Conveyor", location: "Line A" },
  { id: "FIL-01", name: "Filling Machine", location: "Line A" },
  { id: "CAP-01", name: "Capping Machine", location: "Line A" },
  { id: "LBL-01", name: "Labeller", location: "Line A" },
  { id: "PKG-01", name: "Case Packer", location: "Line A" },
  { id: "PB-01", name: "Paint Booth", location: "Finishing" },
  { id: "HYD-01", name: "Hydraulic Press", location: "Machine Shop" },
];

// [from, to] — "from" supplies power, air, water or steam to "to"
export const feeds: [string, string][] = [
  ["GEN-01", "MDB-01"],
  ["MDB-01", "AC-01"],
  ["MDB-01", "CWP-01"],
  ["MDB-01", "FWP-01"],
  ["MDB-01", "CNV-01"],
  ["MDB-01", "HYD-01"],
  ["MDB-01", "PB-01"],
  ["AC-01", "AD-01"],
  ["AD-01", "FIL-01"],
  ["AD-01", "CAP-01"],
  ["AD-01", "PB-01"],
  ["AD-01", "PKG-01"],
  ["CWP-01", "CT-01"],
  ["CT-01", "HYD-01"],
  ["FWP-01", "BLR-01"],
  ["BLR-01", "FIL-01"],
  ["CNV-01", "FIL-01"],
  ["FIL-01", "CAP-01"],
  ["CAP-01", "LBL-01"],
  ["LBL-01", "PKG-01"],
];

export const parts = [
  { id: "BRG-6205", name: "Ball Bearing 6205" },
  { id: "BLT-A42", name: "V-Belt A42" },
  { id: "SEAL-25", name: "Mechanical Seal 25mm" },
  { id: "FLT-AIR01", name: "Air Intake Filter" },
  { id: "FLT-OIL02", name: "Oil Filter" },
  { id: "HOSE-12", name: "Hydraulic Hose 12mm" },
  { id: "SOL-24V", name: "Solenoid Valve 24V" },
  { id: "PLC-M221", name: "PLC Module M221" },
  { id: "MTR-5K5", name: "Motor 5.5kW" },
  { id: "CTR-3P", name: "Contactor 3-pole" },
  { id: "GSK-BLR", name: "Boiler Manhole Gasket" },
  { id: "SGT-01", name: "Sight Glass" },
  { id: "NOZ-SPR", name: "Spray Nozzle" },
  { id: "LBL-SEN", name: "Label Sensor" },
  { id: "CAP-CHK", name: "Capping Chuck" },
  { id: "FIL-NOZ", name: "Filling Nozzle" },
  { id: "CT-FAN", name: "Cooling Tower Fan Blade" },
  { id: "AVR-01", name: "Automatic Voltage Regulator" },
  { id: "DRY-DES", name: "Desiccant Cartridge" },
  { id: "CNV-BLT", name: "Conveyor Belt 4m" },
];

// [equipmentId, partId]
export const hasPart: [string, string][] = [
  ["AC-01", "BRG-6205"],
  ["CWP-01", "BRG-6205"],
  ["FWP-01", "BRG-6205"],
  ["CNV-01", "BRG-6205"],
  ["AC-01", "BLT-A42"],
  ["CNV-01", "BLT-A42"],
  ["CT-01", "BLT-A42"],
  ["CWP-01", "SEAL-25"],
  ["FWP-01", "SEAL-25"],
  ["AC-01", "FLT-AIR01"],
  ["GEN-01", "FLT-AIR01"],
  ["GEN-01", "FLT-OIL02"],
  ["HYD-01", "FLT-OIL02"],
  ["HYD-01", "HOSE-12"],
  ["PB-01", "HOSE-12"],
  ["FIL-01", "SOL-24V"],
  ["CAP-01", "SOL-24V"],
  ["PB-01", "SOL-24V"],
  ["FIL-01", "PLC-M221"],
  ["CAP-01", "PLC-M221"],
  ["LBL-01", "PLC-M221"],
  ["PKG-01", "PLC-M221"],
  ["CNV-01", "MTR-5K5"],
  ["CWP-01", "MTR-5K5"],
  ["MDB-01", "CTR-3P"],
  ["AC-01", "CTR-3P"],
  ["BLR-01", "GSK-BLR"],
  ["BLR-01", "SGT-01"],
  ["PB-01", "NOZ-SPR"],
  ["LBL-01", "LBL-SEN"],
  ["CAP-01", "CAP-CHK"],
  ["FIL-01", "FIL-NOZ"],
  ["CT-01", "CT-FAN"],
  ["GEN-01", "AVR-01"],
  ["AD-01", "DRY-DES"],
  ["CNV-01", "CNV-BLT"],
];

export const technicians = [
  { id: "T-01", name: "Chidi Okeke", trade: "Electrical" },
  { id: "T-02", name: "Amaka Nwosu", trade: "Rotating Equipment" },
  { id: "T-03", name: "Tunde Balogun", trade: "Boiler & Pressure" },
  { id: "T-04", name: "Ifeoma Eze", trade: "Packaging Line" },
  { id: "T-05", name: "Musa Danjuma", trade: "Hydraulics" },
  { id: "T-06", name: "Grace Adeyemi", trade: "Instrumentation" },
];

// [technicianId, equipmentId]
export const certifiedFor: [string, string][] = [
  ["T-01", "GEN-01"],
  ["T-01", "MDB-01"],
  ["T-01", "CNV-01"],
  ["T-02", "AC-01"],
  ["T-02", "CWP-01"],
  ["T-02", "FWP-01"],
  ["T-02", "CT-01"],
  ["T-03", "BLR-01"],
  ["T-03", "FWP-01"],
  ["T-04", "FIL-01"],
  ["T-04", "CAP-01"],
  ["T-04", "LBL-01"],
  ["T-04", "PKG-01"],
  ["T-05", "HYD-01"],
  ["T-05", "PB-01"],
  ["T-06", "FIL-01"],
  ["T-06", "AD-01"],
  ["T-06", "AC-01"],
];
